apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  namespace: url-shortener-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: url-shortener
        env:
        - name: NODE_ENV
          value: "development"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          limits:
            cpu: "300m"
            memory: "384Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"