apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
  namespace: url-shortener
type: Opaque
stringData:
  postgres_user: postgres
  postgres_password: CHANGE_ME_IN_PRODUCTION
  redis_password: CHANGE_ME_IN_PRODUCTION
  rabbitmq_user: rabbitmq
  rabbitmq_password: CHANGE_ME_IN_PRODUCTION
  jwt_secret: CHANGE_ME_IN_PRODUCTION
  clickhouse_user: clickhouse
  clickhouse_password: CHANGE_ME_IN_PRODUCTION