apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
  namespace: url-shortener
data:
  config.json: |
    {
      "logLevel": "info",
      "metrics": {
        "enabled": true,
        "collectDefaultMetrics": true
      },
      "cache": {
        "ttl": 3600,
        "checkPeriod": 600
      }
    }